### PR TITLE
test passwords against zxcvbn

### PR DESCRIPTION
**Pull request by girst**
This PR extends `pass audit` to also flag passwords that are likely weak (using the python implementation of Dropbox's `zxcvbn`). 

 * In order to also compare against usernames, the whole password file will be read in (as opposed to only the first line), so I had to change the accessing of the passwords a bit. 
 * ~~as to not require the user to install the `zxcvbn` python library from pip, I've included it as a git submodule, which will be copied to `/usr/lib/password-store/audit` when `make install` is issued. That means, cloning now should either be done with `git clone --recurse-submodules` or the submodule needs to be otherwise initialized beforehand.~~ made optional
 * some more testing should be done before merging this, but I wanted to get some input before I continue.  ~~(I think I'm not getting all the weak passwords detected, but it's 5am already)~~ i had a `return` too far indented m(

example output:

```
  .  Auditing whole store - this may take some time
  w  Password breached: foobar from bar/foo has been breached 11063 time(s).
  w  Password breached: foofoo from testx has been breached 6668 time(s).
  w  Weak password detected: wkxjzdpl from zdpl/wkxj might be weak. Details: Score 1 (15000 guesses). The password is combined from the following parts: wkxj(dictionary) + zdpl(dictionary)
  w  Weak password detected: foofoo from testx might be weak. Details: Score 1 (2003.0 guesses). The password is combined from the following parts: foofoo(repeat)
 [x] Error: 2 passwords tested and 2 breached, 2 weak passwords found.
  .  You should update them with 'pass-update'.
```

### CODE REVIEW

**Comment by roddhjav** [comment]
That a great PR!! This is a planned feature so I will undoubtedly merge it when it is ready. Congrats!

I still need to look deeper in your implementation, but it seems good. However, I do not agree with your option to add `zxcvbn` as a submodule. It is a dependency and should be installed as every dependency (either with pip or apt-get, pacman, yum...).

**Comment by girst** [comment]
> However, I do not agree with your option to add zxcvbn as a submodule. 

I understand. how do you feel about the compromise in `8a2621e`? running `make` prompts you to install zxcvbn from pip3 or you can use the `zxcvbn` target as a fallback (which provides zxcvbn using the submodule method)

**Comment by girst** [comment]
This is pretty much done now. I've updated the readme to name zxcvbn and added a contributor's section (feel free to remove it though). 

@roddhjav

**Comment by girst** [comment]
>You need to remove the zxcvbn section in the makefile.

done

>unit test for the feature you added (I can do it otherwise).

if you could do that, that'd be great!

**Comment by roddhjav** [comment]
Merged, good work!!

**Comment by girst** [comment]
great! I've just noticed there was a manpage as well :| i have included a mention to zxcvbn and fixed some minor things as well (references to "pass import", "MARK", ...)

I don't feel like opening another pull request, you could just apply it yourself if you want

```patch
diff --git a/pass-audit.1 b/pass-audit.1
index 1e9b8d7..b9e1e73 100644
--- a/pass-audit.1
+++ b/pass-audit.1
@@ -1,4 +1,4 @@
-.TH MARK 1 "February 2018" "pass-audit"
+.TH "pass-audit" 1 "April 2018" "pass-audit"
 
 .SH NAME
 \fBpass audit\fP - A \fIpass\fP(1) extension for auditing your password repository.
@@ -10,7 +10,7 @@
 .SH DESCRIPTION
 \fBpass audit\fP is a password store extension for auditing your password
 repository. It supports safe breached password detection from haveibeenpwned.com
-using K-anonymity method.
+using K-anonymity method and password strength estimation by Dropbox' zxcvbn.
 
 
 .SH COMMAND
@@ -46,11 +46,11 @@ Show usage message.
 
 
 .SH AUTHORS
-.B pass import
+.B pass audit
 was written by
 .MT alexandre@pujol.io
 Alexandre Pujol
-.ME .
+.ME \\ and contributors.
 
 
 .SH COPYING
```

**Comment by roddhjav** [comment]
On the contrary, you should open another PR for it in order to "own" the commit.

**Pull request merged**
